### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [bollu/blog#1]
Hi! I am the editor of Haskell Weekly. An issue from a couple weeks ago (https://haskellweekly.news/issues/92.html) featured your most recent blog post. I would like to be notified when you write a new post, but as far as I can tell your blog does not have a feed. Would you mind adding an Atom or RSS feed? Thanks!

**Comment by bollu** [comment]
Sure, I can do that :) Thanks for the interest!

[Here is a link to the RSS feed](https://pixel-druid.com/index.xml).

Please do get back to me if it works!

**Comment by tfausak** [comment]
Yup, that works for me. Thanks!
